### ISSUE TITLE
WorldTimeLastFired is never set in WeaponFiringComponent

### ISSUE THREAD

**Issue by jjonj** [ZacharyDK/UtilityCombatSample#2] opened 2022-08-08 18:48 UTC
Also if bPassTimingCheck is false but bPassAmmoCheck is true then the weapon will still fire.

**Comment by ZacharyDK** [comment] 2022-08-09 03:03
Should be fixed. See new logic in FirePattern(). 
WorldTimeLastFired is now set before OnWeaponFire.Broadcast()


The extent of my testing was that I didn't break the project and the logic seems to be working as intended. Output logs verify that if bCanFire is false, firing won't happen as intended. This means we can no longer fire if bPassTimingCheck is false but bPaSSAmmoCheck is true. 

My issue was that I forgot to test and exit the function if bCanFire was false for any reason, and i only tested the case bCanFire 

Oh, and autoreload check happens if we can't fire, and need to reload. Or if bCanFire check was passed but clip is empty. 

You'd think that this last check wouldn't matter, but I just like to cover my butt. And I wrote this method almost two years ago, so I'm a bit fuzzy.

Anyway, thanks for finding this bug. I appreciate the help. Marking this closed.

**Closed as completed by ZacharyDK** 2022-08-09 03:03 UTC
